# Generated by Django 2.1.3 on 2021-10-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('commons', '0028_auto_20190919_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sharedlearningpath',
            options={'verbose_name': 'shared LP', 'verbose_name_plural': 'shared LPs'},
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Hrvatski'), ('it', 'Italiano'), ('pt', 'Português'), ('ru', 'Русский'), ('ar', 'Arabic')], default='en', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='status',
            field=models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Hidden'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state'),
        ),
        migrations.AlterField(
            model_name='folderdocument',
            name='state',
            field=models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Hidden'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='state',
            field=models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Hidden'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state'),
        ),
        migrations.AlterField(
            model_name='oer',
            name='state',
            field=models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Hidden'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='state',
            field=models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Hidden'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state'),
        ),
    ]
