# Generated by Django 2.1.3 on 2021-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0030_auto_20211219_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_new_posts_notification',
            field=models.BooleanField(default=True, help_text='Do you want being notified by email when new forum posts are present?.', verbose_name='get notification of unread forum posts'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='enable_email_notifications',
            field=models.PositiveIntegerField(choices=[(0, 'do not notify me of new private messages'), (1, 'notify me only of individual messages'), (2, 'notify me of individual and group messages')], default=0, help_text='Do you want that private messages from other members be notified to you by email? In any case, they will not know your email address.', null=True, verbose_name='get notification of private messages'),
        ),
    ]
